### ISSUE TITLE
0.1.6 breaks IE11 compatibility

### ISSUE THREAD

**Issue by jonathanmoffatt** [richardtallent/vue-object-merge#2]
Hi Richard,
[This commit in 0.1.6](https://github.com/richardtallent/vue-object-merge/commit/e0e882ab4a5fc61c16eedfb3d9f878175af5f5b0) breaks IE11 compatibility. Works fine still against 0.1.5.

**Comment by richardtallent** [comment]
Sorry for the late reply... I don't have access to test IE11 anymore, can you provide more information?

@OmgImAlexis, since you authored the module support added in 0.1.6, would you be able to provide some insight on this?

**Comment by OmgImAlexis** [comment]
@jonathanmoffatt you'll likely need to use the [`babel-plugin-transform-es2015-arrow-functions`](https://babeljs.io/docs/en/babel-plugin-transform-es2015-arrow-functions) babel plugin.

The reason you need this is that IE11 doesn't support fat arrows.

**Comment by richardtallent** [comment]
Ah! Since we don't strictly need an fat arrow, I've reverted it back to a plain old function. Published as 0.1.7. @jonathanmoffatt, please re-open if this doesn't resolve the issue. Thanks!
