### ISSUE TITLE
One more caveat

### ISSUE THREAD

**Issue by louisameline** [richardtallent/vue-object-merge#4]
I noticed that I had a computed watching an object property that doesn't necessarily exist at first, like
```javascript
computed: {
  thing () {
    if (someObject.archived) {
      ...
    }
  }
}
```
Even if the object itself is reactive, adding the `archived` property afterwards won't trigger reactivity. You either have to
- set the `archived` property from the beginning (to `false` for example)
- replace the object itself, and not add the property to it

It's reactivity 101, but I had not anticipated this before I noticed the issue.
Thank you

**Comment by richardtallent** [comment]
Yes, the computed property works by setting up a watch on the property requested, so if that property doesn't exist, it can't initialize properly and thus can't watch for changes. Just a consequence of how Vue works. I'm not sure if the proxy-based changes coming to Vue will make a difference either -- I suspect not.

**Comment by louisameline** [comment]
I opened the ticket in the hope that maybe it could be added to the doc, but as you wish. Thanks
